

volume:
  db:

services:
  db:
    image: "postgres:14"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: q1fs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
